account:
    peerId: 12D3KooWA8EXV3KjBxEU5EnsPfneLx84vMWAtTBQBeyooN82KSuS
    peerKey: psqF8Rj52Ci6gsUl5ttwBVhINTP8Yowc2hea73MeFm4Ek9AxedYSB4+r7DYCclDL4WmLggj2caNapFUmsMtn5Q==
    signingKey: 3MFdA66xRw9PbCWlfa620980P4QccXehFlABnyJ/tfwHbtBVHt+KWuXOfyWSF63Ngi70m+gcWtPAcW5fxCwgVg==
drpc:
    stream:
        maxMsgSizeMb: 256
mongo:
    connect: mongodb://localhost:27017
    database: anynsnode
yamux:
    listenAddrs:
        - 127.0.0.1:4830
    writeTimeoutSec: 10
    dialTimeoutSec: 10
network:
    id: 64ba63209976be4a733bbb91
    networkId: N4Gvo3v5wL31RrYgX3PrhAGMYvdWe5rAgtVB8cZySYWrkhb6
    nodes:
        - peerId: 12D3KooWA8EXV3KjBxEU5EnsPfneLx84vMWAtTBQBeyooN82KSuS
          addresses:
            - 127.0.0.1:4830
          types:
            - coordinator
    creationTime: 2023-07-21T11:51:12.970882+01:00
networkStorePath: .
log:
  production: false
contracts:
  geth_url: https://sepolia.infura.io/v3/XXX
  registry: 0xfDA2A52fB6407Ae5c35Dff96837c6d5768c76a79 
  resolver: 0x2E6B72443612bDDd668BB60b18a030cb6aE806CE 
  registrar: 0xB6bF17cBe45CbC7609e4f8fA56154c9DeF8590CA 
  private_controller: 0x1120Ac6114CEc38Ccd66a45e0D612f159876980E 
  name_wrapper: 0xC68FC50baebA616916C390d035Cf485d8F039d21
  admin: 0x61d1eeE7FBF652482DEa98A1Df591C626bA09a60
  token: 0x8AE88b2b35F15D6320D77ab8EC7E3410F78376F6
  admin_pk: XXX
  wait_mining_retry_count: 5
queue:
  skip_processing: false
  skip_background_processing: false
  nonce_retry_count: 10
  high_nonce_retry_count: 2
accountAbstraction:
  alchemyRpcUrl: https://eth-sepolia.g.alchemy.com/v2/YYY
  accountFactory: 0x123
  entryPoint: 0x234
  gasPolicyId: 123
  alchemyApiKey: xYZ_aBC
  chainID: 11155111